url: https://lilhandsbgdreams.github.io

# Site settings
title: lilhandsbgdreams
email: 
description: ""


# Team names, titles and social links
people:
- name: lilhandsbgdreams
  pic: 1
  position: Web Developer
  social:
    - title: github
      url: https://github.com/lilhandsbgdreams

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/lilhandsbgdreams

# Build settings
markdown: kramdown
permalink: pretty
